#ifndef FILM_HPP
#define FILM_HPP

#include <cstdint>

#include "common.hpp"
#include "geometry.hpp"
#include "paramset.hpp"

namespace gc {

using byte = std::uint8_t;

/// Represents an image generated by the ray tracer.
class Film {
public:
  /// List of support image file formats.
  enum class image_type_e : byte { PNG = 0, PPM3, PPM6 };

  //=== Film Public Methods
  Film(const Point2i& resolution,
       const std::string& filename,
       image_type_e image_type,
       bool gamma_corrected = false);
  virtual ~Film();

  /// Retrieve original Film resolution.
  [[nodiscard]] Point2i get_resolution() const { return m_full_resolution; };

  /// Takes a sample `p` and its radiance `L` and updates the image.
  void add_sample(const Point2i&, const Spectrum&) const;

  /// Write image to file.
  void write_image() const;

  //=== Film Public Data
  const Point2i m_full_resolution;  //!< The image's full resolution values.
  // Bounds2i m_crop_pix_bounds;        //!< Crop window in pixel (raster) coordinates.
  std::string m_filename;            //!< Full path file name + extension.
  bool m_activate_gamma_correction;  //!< Gamma correction flag, requesting the correction if on.
  image_type_e m_image_type;         //!< Image type, PNG, PPM3, PPM6.

  // TODO: This class is incomplete!
  /// Reference to the color buffer (image) object.
  // std::unique_ptr<ColorBuffer> m_color_buffer_ptr;
};

/// Factory creation
Film* create_film(const ParamSet& ps);

std::string handles_filename(const ParamSet& ps);
// gc::Bounds2f handles_cropwindow(const ParamSet& ps);
gc::Point2i handles_dimensions(const ParamSet& ps);

}  // namespace gc

#endif  // FILM_HPP
